theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "speedtest"
interval = 640

[[block]]
block = "music"
player = "mpd"
buttons = ["prev", "play", "next"]

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "wlp3s0"
# ssid = true
# ip = true
# speed_up = false
# graph_up = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
# ssid = false
# signal_strength = false
# ip = true
# speed_up = false
# graph_up = false
interval = 5
# use_bits = false

[[block]]
block = "net"
device = "ens1u2u1u2"
# ssid = false
# signal_strength = false
# ip = true
# speed_up = false
# graph_up = false
interval = 5
# use_bits = false
