[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome5"

[[block]]
block = "custom"
command = '''if makoctl mode | grep -q 'dnd'; then echo "DND"; else echo "No DND"; fi'''
interval = 15
[[block.click]]
button = "left"
cmd = "makoctl mode -t dnd"
sync = true
update = true

[[block]]
block = "custom"
command = '''printf "Mails in queue: %d" $(ls ~/.local/share/msmtp/queue/*.mail | wc -l)'''
interval = 15
[[block.click]]
button = "left"
cmd = "msmtp-queue -r"
sync = true
update = true

# [[block]]
# block = "speedtest"
# interval = 640

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "^wlp.*$"
format = "$icon {$ssid $signal_strength $frequency|Wired connection} $ip"
format_alt = "{$ssid|Wired connection} $ipv6 $speed_down.eng(prefix:M)"
interval = 20
# hide_inactive = true

[[block]]
block = "net"
device = "^enp.*f.*"
format = " $icon $bitrate $ip "
format_alt = " $ipv6 $speed_up.eng(prefix:M) $speed_down.eng(prefix:M) "
interval = 20
missing_format = ""

[[block]]
block = "net"
device = "^enp.*u.*"
format = " $icon $ip "
format_alt = " $ipv6 $speed_up.eng(prefix:M) $speed_down.eng(prefix:M) "
interval = 5
missing_format = ""
