theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "custom"
command = '''ls ~/.local/share/msmtp/queue | wc -l | printf "Mails in queue: %d"'''
on_click = "msmtp-queue -r"
interval = 15

[[block]]
block = "speedtest"
interval = 640

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid} {signal_strength} {ip} {frequency}"
format_alt = "{ssid} {ipv6} {speed_down;K*b}"
interval = 20
hide_inactive = true

[[block]]
block = "net"
device = "enp0s31f6"
format = "{bitrate} {ip}"
format_alt = "{ipv6} {speed_up;K*b} {speed_down;K*b}"
interval = 20
hide_inactive = true

[[block]]
block = "net"
device = "enp9s0u1"
format = "{bitrate} {ip}"
format_alt = "{ipv6} {speed_up;K*b} {speed_down;K*b}"
interval = 5
hide_inactive = true
hide_missing = true
